DROP TABLE public.elections;

CREATE TABLE public.elections
(
    id_no character varying,
    "na" character varying,
    "na_value" character varying,
    "na_name" character varying,
    sr character varying,
    "candidate_name" character varying(120) COLLATE pg_catalog."default",
    "party" character varying COLLATE pg_catalog."default",
    party1 integer,
    party_93 integer,
    nnparty character varying,
    "votes" bigint,
    "rvotes" numeric(6,2),
    "vote_lead_PML_N_Q" bigint,
    nvote_lag character varying,
    diff_runner_up bigint,	
    ndiff_runner_up	integer, 
    turn_out numeric(20,8),	
    nturn_out numeric(20,8),	
    nndiff_runner_up integer,	
    vote_lag bigint,	
    winner_percentage numeric(20,8),	
    winner_runner_prop numeric(20,8),	
    valid_votes bigint,	
    rejected_votes bigint,	
    total_votes bigint,	
    registered_voters bigint,	
    district character varying,	
    ndistrict integer,	
    prov integer,	
    year integer,	
    filter_$ integer,	
    candiates integer,	
    per_na_one_case integer,	
    zones_20 integer,	
    regions_12 integer,	
    regions_8 integer,	
    nnnparty integer,	
    party_lead_PML_N_Q integer, 
    nnnnparty integer,	
    votes_others bigint,	
    votes_excluding_N bigint,	
    type integer,	
    winning_party integer,	
    nwinning_party integer,	
    nnwinning_party integer,	
    temp_year integer,	
    a bigint,	
    party_lead_ppp integer,	
    vote_lag_PML_Q bigint,	
    party_lag_PML_Q integer,	
    votes_PML_Q bigint,	
    votes_PML_N	bigint, 
    votes_PPP bigint,	
    vote_lead_PPP bigint,	
    division integer,	
    regions_11 integer,	
    temp_Pro integer,	
    temp_Party_93 integer,	
    ap integer,	
    merge_party integer,	
    party_97 integer,	
    party_97_string character varying,	
    temp_Party_97 integer,	
    party_02 integer,	
    temp_Party_02 integer,	
    party_08 integer,	
    temp_Party_08 integer,	
    party_90 integer,	
    temp_Party_90 integer,	
    party_88 integer,	
    temp_Party_88 integer,	
    t_out character varying,	
    party_77 integer,	
    na_district integer,	
    temp_totalvotes numeric(20,2),	
    votes_N_Q bigint,	
    party_70 integer,	
    votes_polled bigint,	
    PercentageofVotesPolledtoRegisteredVoters numeric(10,3),	
    winner character varying,	
    ndivision integer,	
    nzones_20 integer,	
    nregions_12 integer,	
    nregions_11 integer,	
    nprov integer,	
    party_2013 integer,	
    ID_Respondent bigint,	
    n_registerd integer,	
    ap1 integer--,    
--	CONSTRAINT elections_pkey PRIMARY KEY (id_no)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.elections
    OWNER to zohaib;

COPY elections FROM '/Users/zohaib/pak-elections/Pakistan_Election_Results_1970_2013_Cleaned_2.csv' WITH (FORMAT csv, HEADER, NULL ' ', ENCODING 'windows-1251');

SELECT * FROM public.elections;

